### ISSUE TITLE
TestSimpleMetrics is failed

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1029]
## Expected Behavior

TestSimpleMetrics should pass

## Current Behavior

TestSimpleMetrics is failing.

## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by denis-tingajkin** [comment]
Can this be closed?

**Comment by alex-yust** [comment]
Failed again..
https://circleci.com/gh/networkservicemesh/networkservicemesh/104734#tests/containers/0

**Comment by denis-tingajkin** [comment]
In this issue, the problem was in the monitoring period... 
I found in logs from CI, that the notification server from vpp-agent side is not working as expected.
 
For example, metrics logs from master branch:

```Metrics collector: request 0
Metrics collector: request 1
Metrics collector: request 2
```

Metrics logs from failing branch:
```
Metrics collector: request 0
Metrics collector: request 0
Metrics collector: request 0
```
So I think the problem on vpp-agent side (but we need to approve this). I think it is a new problem and it is not related to this issue.
