### ISSUE TITLE
usecase_vpn_test tests are failing inconsistently

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/networkservicemesh#1152]
## Expected Behavior

All tests from `usecase_vpn_test.go` should always pass.

## Current Behavior

These tests are inconsistently failing on GKE and packet:
* TestVPNLocal
* TestVPNFirewallRemote
* TestVPNNSERemote
* TestVPNNSCRemote

## Failure Information (for bugs)
https://circleci.com/gh/networkservicemesh/networkservicemesh/53948
https://circleci.com/gh/networkservicemesh/networkservicemesh/54094
https://circleci.com/gh/networkservicemesh/networkservicemesh/54051
https://circleci.com/gh/networkservicemesh/networkservicemesh/54211

**Comment by Bolodya1997** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/54512
https://circleci.com/gh/networkservicemesh/networkservicemesh/54352

**Comment by Bolodya1997** [comment]
Still happening sometimes:
https://circleci.com/gh/networkservicemesh/networkservicemesh/64763

**Comment by lobkovilya** [comment]
Failed because sibling packet job has failed and started deleting all packet clusters:
https://circleci.com/gh/networkservicemesh/networkservicemesh/53948
https://circleci.com/gh/networkservicemesh/networkservicemesh/54051
https://circleci.com/gh/networkservicemesh/networkservicemesh/54352

Failed because of 30m timeout exceeded:
https://circleci.com/gh/networkservicemesh/networkservicemesh/54094
https://circleci.com/gh/networkservicemesh/networkservicemesh/54211
https://circleci.com/gh/networkservicemesh/networkservicemesh/54512

**Comment by Bolodya1997** [comment]
Still failing:
https://circleci.com/gh/networkservicemesh/networkservicemesh/69695
