### ISSUE TITLE
pods depending on networkservicemeshci/nsm-init:latest fail

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/networkservicemesh#1342]
While attempting to build and deploy the nsm bridge-domain example in the examples repo, came across this problem:

```
  Normal   Pulling    40s (x3 over 80s)  kubelet, nsm-worker2  Pulling image "networkservicemeshci/nsm-init:latest"
  Warning  Failed     39s (x3 over 79s)  kubelet, nsm-worker2  Failed to pull image "networkservicemeshci/nsm-init:latest": rpc error: code = Unknown desc = failed to resolve image "docker.io/networkservicemeshci/nsm-init:latest"
```

In short, nsm-init:latest does not exist in the networkservicemeshci repo. We should either point to networkservicemesh/nsm-init or public a "latest" tag.

**Comment by fkautz** [comment]
I tested this with nsm installed via the make machinery and with helm. I get the same behavior.

**Comment by fkautz** [comment]
Reopening, this issue wasn't resolved yet.

**Comment by denis-tingajkin** [comment]
I can take a look. Assign the issue on me if you don't mind

**Comment by nickolaev** [comment]
So, in general, we do not have "latest", except when you do local development. That is what will be used only in this case, for everything else (i.e. helm) we should use master or any of the future "release" tags. For the make file, one can use the CONTAINER_TAG env.

The other problem was that "networkservicemeshci" was hardcoded as a repo when deploying the webhook by "make". That is fixed now by setting CONTAINER_REPO for the make files.

So I am not sure what exactly the problem is now, but it is a matter of setting the proper env and/or fixing the helm charts.

**Comment by nickolaev** [comment]
I have just found that we actually do not corelate the webhook and nsm-init in the makefile machinery, therefore the nsm-init image is not loaded.

**Comment by fkautz** [comment]
@nickolaev i was able to verify that when the nsm-init is loaded manually via kind, it works.

**Comment by fkautz** [comment]
Should be resolved.
