### ISSUE TITLE
vni conflict in vxlan connecitons

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/networkservicemesh#1354]
## Expected Behavior

vni should be unique for each connection between two clusters

## Current Behavior

Two remote connections can have the same vni value

## Failure Information (for bugs)

Current vni selector script does not guarantee that there is no vni conflict in connections between two clusters

https://github.com/networkservicemesh/networkservicemesh/blob/54548ed42f1d0c3de6071c873412b58e68eaf690/controlplane/pkg/vni/vni.go#L39-L52

## Steps to Reproduce

Disabled TestInterdomainVPNFirewallRemote integration test in pr #1298 has almost 100% chance to reproduce issue on clouds

## Failure Logs

[log.txt](https://github.com/networkservicemesh/networkservicemesh/files/3395084/log.txt)

**Comment by nickolaev** [comment]
I don't like the way we reference VNI in the middle fo the control plane. NSMgr should be pretty much remote mechanism agnostic and have an abstract pool of connection IDs where the local forwarding planes translate them to the specific IDs that the selected tunnelling protocol uses. So imagine we want to enable MPLS now, we have to map the VNIs to labels.

**Comment by edwarnicke** [comment]
@nickolaev I don't quite follow... could you say more?

**Comment by nickolaev** [comment]
One of the NSM building blocks is the point-to-point connection between the workloads. When we want to connect remote workloads we rely on a unique identifier to establish that point-top-point connectivity without interfering with the other workloads sharing the same physical infrastructure. 

In the current code, the unique ID, that is supposed to distinguish the tunnel is called VNI, which more or less suggests VxLAN. I prefer if we move away from that wording, and be more generic here - TunnelID or similar might be better named. Then we also need to find a suitable size of that id. VNIs are 24-bit which is plenty but maybe we want to go with 32 or even 64 bit IDs. We can even do UUIDs if we find that better. Then these abstract IDs can be passed to the forwarding plane alongside the cross-connect request (as done today) and let the forwarding plane figure out how the 64-bit ID (for example) maps to the 24-bit VNI.

As I proposed in my previous comment - these IDs can be generated out of the domain/host names, or maybe split the whole 64-bit(range) into chunks and distribute them to the NSMgrs etc.

**Comment by edwarnicke** [comment]
@nickolaev VNIs are bound to the particular mechanism choice (in this case VXLAN)... different mechanism types will have different kinds of parameters (example: SRv6 and SID lists)... so I think this is more an issue of proper binding of parameters to mechanisms, rather than trying to build a one size fits all parameters.

All of that said, I think the issue that @artem-belov is raising here is about *how* we assign the VNI.

Currently, the last NSMgr in the chain assigns the VNI as part of accepting the connection, and it does it by comparing its IP address to the SRC_IP for the tunnel.  Depending on the outcome of that comparison it will choose to assign either odd or even VNIs when it receives a Request from *this particular peer*.  The reason it does this is to avoid a central ID issuing authority.  Since given two peers (NSMgr1, NSMgr2) you can have:

NSMgr1 Requests of NSMgr2 (and therefore NSMgr2 picks the VNI) or
NSMgr2 Requests of NSMgr1 (and therefore NSMgr1 picks the VNI)

and since in the case of VXLAN, its (src_ip, dst_ip, vni) that uniquely determine the tunnel, this approach let us avoid complex coordination.

What @artem-belov is pointing out is that due to NAT-like behaviors in inter-domain, we may have situations where NSMgr1 Requests via a pNSMgr to NSMgr2 ... and the pNSMgr may be munging tunnel IPs to deal with Public/Private IP situations.

So NSMgr1 thinks its dealing with the pair (private_src_ip, public_dst_ip) and NSMgr2 sees (public_src_ip,private_dst_ip).  This can cause them to arrive at situations via IP address comparison where NSMgr1 believes it should select from the odd VNIs when NSMgr2 requests of it... and NSMgr2 believes it should *also* select from the odd VNIs when NSMgr1 requests of it.

**Comment by nickolaev** [comment]
I get what are the reasons behind this code, but my argument here is that this code does (parsin IPs and figuring out ~VNIs) does not belong to NSMgr, but to the concrete forwarding plane implementation. From your explanation it sounds like we'll have to add `networkservicemesh/controlplane/pkg/sni/sni.go` once we want to add SR. and then choose at runtime which ID allocation mechanism to call depdning on the remote mechanism chosen. And I think this logic does not belong in NMgr. It's forawrding plane's job to figure out remote mechanism details- IMO.

**Comment by edwarnicke** [comment]
@nickolaev Ah... got it.  So I think we have two issues here:

1.  Where this sort of logic should live.  I get your point about putting it in the NSM Forwarder.  To do so, we will need to make some alterations to the NSM Forwarder API, but they are arguably overdue.  I would suggest we open a new issue for that
2.  Fixing the selection algorithm for VNIs in this sort of case. 

Does that sounds like a fair split of the issue to you?

**Comment by nickolaev** [comment]
@edwarnicke yes, this is a good split. Thanks.

**Comment by edwarnicke** [comment]
@artem-belov Do you have suggestions for ways to handle the VNI problem here?

**Comment by haiodo** [comment]
Guys, correct me, probable I'm wrong, but in this example it probable will also fail:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/477235/62153577-15aced00-b32f-11e9-82c5-fbfc4bdfed72.png">

**Comment by edwarnicke** [comment]
@haiodo I don't think so... in this example the VXLAN/VNI1 is for the vWire between Dataplane1 and Dataplane2 ... Vxlan/VNI2 is for the vWire between Dataplane2 and Dataplane3... so it should work (if I understand your example correctly).

**Comment by haiodo** [comment]
In this example it should also fail:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/477235/62153817-9cfa6080-b32f-11e9-8520-6dc0136cdd21.png">

**Comment by haiodo** [comment]
@edwarnicke , I’ve found error in my drawing so updated :slightly_smiling_face:
Question is when we need vxlan from dataplane3 to dataplane1

**Comment by edwarnicke** [comment]
@haiodo I'd been thinking about it as Dataplane2 being responsible to crossconnect there.
So Dataplane1 crossconnects Client to VXlan/VNI1, Datplane2 crossconnects VXlan/VN1 to VXLAN/VNI2, and Dataplane3 cross connects from VXLAN/VNI2 to the Endpoint.

I'm not sure what to make of your VXLAN/VNI3 directly from the Endpoint... ;)

**Comment by artem-belov** [comment]
@haiodo @edwarnicke @nickolaev  I think we can make kind of a handshake of NSMs on first request. For example, NSMgr1 doesn't find NSMgr2 address in the VNIs map, so it makes a request to split up VNI range.
Another way - we can wind some unique property to compare NSMs and choose range (Like we are doing now with ip address)

**Comment by artem-belov** [comment]
@edwarnicke After @onobrod will prepare interdomain as plugin, it will keep both  Internal and External IPs information. So we can compare public IPs (local IPs if public are missing or equal) to generate vni. It should resolve problem

**Comment by edwarnicke** [comment]
@artem-belov Please say more... I don't quite follow what you are proposing.

**Comment by artem-belov** [comment]
@edwarnicke 
Current vni generation depends on comparing ip addresses:
src-ip > dst-ip - even vni
dst-ip < src-ip - odd vni

In Interdomain we have to configure VXLAN next way:
src vxlan side: src-internal-ip -> dst-external-ip (vni x)
dst vxlan side: dst-internal-ip -> src-external-ip (vni x)

The cause of current vni conflict is comparing internal ip with external ip which is gives simmetric result sometimes. 
src-internal-ip > dst-external-ip - event vni
dst-internal-ip > src-external-ip - even vni

So we want to keep both internal and external IPs in mechanism preferences to make correct comparing for vni generation. We will compare public IPs for interdomain and local IPs for connection within one cluster

**Comment by haiodo** [comment]
Closing, since merged.
