### ISSUE TITLE
Becoming a Kubernetes WG Member

### ISSUE THREAD

**Issue by lixuna** [networkservicemesh/networkservicemesh#207]
Upstream ticket: https://github.com/kubernetes/community/pull/2372

**Comment by lixuna** [comment]
7/27/2018: In progress

**Comment by mestery** [comment]
I think instead of a Kubernetes WG we should strive to become a [CNCF sponsored project](https://github.com/cncf/toc/blob/master/process/project_proposals.adoc). This is my personal preference, there are obvious benefits to such an arrangement. /cc @fkautz for his comments as well. If we move in this direction, I propose changing the title of this issue. 😃
