### ISSUE TITLE
WireGuard remote mechanism support for vppagent forwarder

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/networkservicemesh#2105]
WireGuard remote mechanism support for vppagent forwarder is required.

## Docs

https://docs.google.com/document/d/1Cgmr5hDJJNI4YLXXarMbqZRvq1Zoe7HCY8a8hwl6JKo //case **Memif full userspace datapath**

**Comment by denis-tingajkin** [comment]
The question to vpp related to problem connect AF_PACKET and tun: https://lists.fd.io/g/vpp-dev/message/15678

**Comment by denis-tingajkin** [comment]
With this issue, I also tried to do the next thing:

Patch `AF_PACKET` interface on vpp side to make it works as `l3` interface.
I'd found that AF_PACKET interface was designed as L2 and to patch it we will need to do many changes (Looks like better create a separate interface type instead of Patch `AF_PACKET`)

**Comment by denis-tingajkin** [comment]
Doc with a decomposition of most popular ways to fix this problem: https://docs.google.com/document/d/1ICYb2kV48l-T1qounqkUBetUAmme0znD9gl405HJ2VQ/edit?usp=sharing

@edwarnicke , @fkautz , @haiodo please take a look and share your thoughts.

**Comment by denis-tingajkin** [comment]
finally blocked by https://github.com/networkservicemesh/networkservicemesh/issues/2137
