### ISSUE TITLE
SR-IOV plugin

### ISSUE THREAD

**Issue by PPaviii** [networkservicemesh/networkservicemesh#2147]
## Overview

Hello everyone, I am Francesco Pavan, a master of science student at Politecnico di Torino, Italy. I am currently investigating NSM technology for my master thesis in collaboration with TIM (Telecom Italia). 
I would like to ask you:
- is further documentation of SR-IOV functionality available anywhere?
- are there any available examples/tests of this functionality?

Thank you!   

## References
This is the issue where SR-IOV plugin is mentioned:
https://github.com/networkservicemesh/networkservicemesh/issues/2139

**Comment by haiodo** [comment]
HI @PPaviii not yet actually, it was previous SR-IOV plugin exist in v0.2 release branch, but it is not integrated into usable examples, documentation. We are in progress to rethink it completely.

https://github.com/networkservicemesh/networkservicemesh/tree/release-0.2/controllers/sriov-controller

**Comment by PPaviii** [comment]
Hi @haiodo, thank you for the reply! Ok everything is clear, one last question:
- do you have a roadmap of the development process or an expected release date?

**Comment by rdimitrov** [comment]
@PPaviii Feel free to reach out if you have questions about configuring the Kubernetes cluster - setup of the SR-IOV VFs, CNI, Device Plugin, etc. 👍

**Comment by PPaviii** [comment]
Hi @rdimitrov, thanks for your availability! How can I reach you to explain my situation and my problems?

**Comment by rdimitrov** [comment]
@PPaviii You should be able to find me in Slack (CNCF's workspace), look for Radoslav Dimitrov 👍

**Comment by fkautz** [comment]
@PPaviii Hello, it's good to meet you. I am one of the maintainers of NSM. @rdimitrov discussed your situation with me.

Are you able to send me a message on slack? We may have resources available. I'd like to discuss what your goals are so that we can work out our options. I'll forward you a link where you can set up a call with me.

I'm currently in PST time (California), so we'll need to work out time zone issues. Please excuse the delay on responses.
