### ISSUE TITLE
Compiler error, on Windows 10

### ISSUE THREAD

**Issue by advancedwebdeveloper** [networkservicemesh/networkservicemesh#2206]
Hi.
I tried to build NSM project, using Windows 10 build of Golang 1.15.2 (x86_64).

> ~/Desktop/networkservicemesh/applications/nsmrs/cmd (master)
> $ go run main.go
> go: downloading github.com/opentracing/opentracing-go v1.1.0
> go: downloading github.com/golang/protobuf v1.3.2
> go: downloading google.golang.org/grpc v1.27.0
> go: downloading github.com/uber/jaeger-client-go v2.17.0+incompatible
> go: downloading github.com/spiffe/go-spiffe v0.0.0-20191104192205-d29ac0a1ba99
> go: downloading golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa
> go: downloading github.com/uber/jaeger-lib v2.1.1+incompatible
> go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.2
> go: downloading google.golang.org/genproto v0.0.0-20200128133413-58ce757ed39b
> # github.com/networkservicemesh/networkservicemesh/pkg/tools
> ..\..\..\pkg\tools\tools.go:64:31: undefined: syscall.Stat_t

**Comment by advancedwebdeveloper** [comment]
Looks like it is about [this](https://github.com/golang/go/issues/1405#issuecomment-66054017) issue

**Comment by edwarnicke** [comment]
@advancedwebdeveloper That appears to be in a utility function to get the current Network Namespace (a Linux feature I do not believe we have in Windows).

While we are taking care to get as much of the multi-repo work as we can so it still compiles and tests across MacOS/Windows... the networkservicemesh/networkservicemesh monorepo is probably mostly going to only work on Linux.

**Comment by advancedwebdeveloper** [comment]
So [this](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-isolation-security) is not what you would require, on Windows containers?
Or it is the right thing?

**Comment by advancedwebdeveloper** [comment]
CC @DCtheGeek

**Comment by TBBle** [comment]
#2177 changed it from a "fails at runtime on Windows" failure to a "fails to compile for Windows" failure.

I don't know enough about this project to know if "fails at runtime on Windows" was correct for whatever functionality is needed (i.e. it's never called on WIndows), or whether someone needs to work out how to get the equivalent of an netns out of a Windows container so that (if I'm skimming correctly) code living outside the container can configure its network interfaces.

**Comment by edwarnicke** [comment]
> So [this](https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-isolation-security) is not what you would require, on Windows containers?
> Or it is the right thing?

OK... now I'm excited.  I'd be delighted to find out there are ways to get to full functionality on Windows.  Its just not an OS I know much about.  If folks can point to the appropriate analogous things in Windows, I'd be super super happy to get them proper support.

The thing we are tripping across here is a mechanism whereby a non-privilged container is providing information over GRPC about its network namespace (in this case getting the inode number of the netns from  /proc/self/ns/net and sending that along) and then we are using that to get a file for that network namespace such that we can insert an interface into it (that second half done by a fully privileged container, couldn't be done otherwise).  How would the analogous trick work in Windows?

**Comment by TBBle** [comment]
Windows Network Namespaces are [identified by GUID](https://docs.microsoft.com/en-us/windows-server/networking/technologies/hcn/hcn-scenarios#scenario-hcn-namespace). I'm not sure how you would get the GUID for the current network namespace from inside the container. Perhaps calling [`hcn.ListNamespaces`](https://github.com/microsoft/hcsshim/blob/852530648bb5e5ce402861b52fb72b45c9c20c3b/hcn/hcnnamespace.go#L224-L232) inside the container would only show your own namespace? I suspect the relevant services (HNS, HCS) are not even running inside a container though.

Kubernetes doesn't currently have privileged containers support [for Windows](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#feature-restrictions). CSI node plugins for example work around this with a daemon ([csi-proxy](https://github.com/kubernetes-csi/csi-proxy)) running on the host. So you'd probably need something similar, something that can make [HNS](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#networking) calls to the host OS to manage the virtual NICs attached to the containers.

The Google Docs-hosted proposal attached to the [Windows privileged containers](https://github.com/kubernetes/enhancements/issues/1981) KEP mentions 'HNS Proxy' which I assume is like csi-proxy but for HNS calls, but I'm unable to locate such a thing with a brief search. It also says this:
> Privileged containers will also enable service mesh support on Windows by enabling the creation of an init container that can configure HNS.

but that whole KEP's a few Kubernetes releases away at best.
