### ISSUE TITLE
Could not find endpoint with name at local registry

### ISSUE THREAD

**Issue by LionelJouin** [networkservicemesh/networkservicemesh#2230]
## Expected Behavior
When deploying a NSC, it should be connected to all NSEs.

## Current Behavior
If a NSC and a NSE are running on 2 different nodes, and the NSC requests the connection to this NSE (using its name in the request), the request fails and returns an error. 
I tried with only 1 node, 1 NSC and 2 NSEs, this is working correctly, the NSC receives the connections to the 2 NSEs.

## Failure Information (for bugs)
I created a new init container that uses the NSM API function "FindNetworkService" (service: "NetworkServiceDiscovery") to get all NSEs. And this init container is requesting the connection with all NSEs using the NSM API function "Request" (service: "NetworkService")

## Steps to Reproduce
1. Create a new init container that fetch the list of NSEs and that request the connection to all NSEs using the name of the NSEs (NetworkServiceEndpointName in the NetworkServiceRequest)
2. Build the images and deploy NSM with this new init container in the admission-webhook specs on a Kubernetes cluster with at least 2 nodes
3. Deploy a NSE on the first node and a NSC on the second node
4. Check the logs of the init container in the NSC

## Context
Ubuntu 18.04
Docker 19.03
Kubernetes 1.19
Xcluster, 2 nodes
Same issue for VPP and Kernel Forwarder 
NSM mono-repo from master (cb2e62e24eb38c3ff7faa62f8e78ff8af197f675)

## Failure Logs
```
time="2021-01-29T09:37:13Z" level=info msg="rpc error: code = Unknown desc = NSM:(7.1.5) <nil>. Last NSE Error: Could not find endpoint with name: full-meshf2dfd at local
registry"
```

**Comment by Tiberivs** [comment]
@LionelJouin could you provide sources of your custom init container?

**Comment by LionelJouin** [comment]
I'd need to discuss sending any code with my team, in the meantime, here are the full logs. Is there anything I could try out or investigate that could be helpful?

I should also mention, after getting all NSEs using the network service discovery, the NSC uses the network service endpoint name attribute in addition to the labels in the connection to request the connection with all NSEs.

[logs.zip](https://github.com/networkservicemesh/networkservicemesh/files/5944781/logs.zip)

**Comment by edwarnicke** [comment]
Had  nice chat with @johlj on slack.

He traced down the origin of the error to:

https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/remote/endpoint_selector_service.go#L59-L66

The remote chain is normally the chain used when the request is coming in from another Node, and so normally only looks for local NSEs.  The question is: how did a request from a node local NSC arrive here?

the remote.EndpointSelectorService is instantiated at:

https://github.com/networkservicemesh/networkservicemesh/blob/104e735fcbf11796dbf80e17ff997c975a67a98a/controlplane/pkg/remote/remote_network_service_server.go#L24-L36

Which is then itself called to instantiate here:

https://github.com/networkservicemesh/networkservicemesh/blob/104e735fcbf11796dbf80e17ff997c975a67a98a/controlplane/pkg/nsmd/nsmd.go#L506-L506

I strongly suspect if we keep chasing this back through the code... we will find a place where we are deciding to use this 'remote' (ie, the request originated remotely) rather than 'local' (ie, the request originated locally) based on whether the NSE name is set in the request.  That's what I'd suggest looking at.

**Comment by edwarnicke** [comment]
> @LionelJouin could you provide sources of your custom init container?

@Tiberivs I'd suggest just trying to have an NSC send a valid NSE name to reproduce.  I believe they are doing this by having the NSC do a lookup on an NS and then picking one.  Should be easy to reproduce :)  Getting their code would be helpful, but lets not block on that.

**Comment by denis-tingaikin** [comment]
@LionelJouin Should be fixed. Could you re-test with the latest master?

**Comment by LionelJouin** [comment]
Hi, I just re-tested and, it is now working correctly, thank you.

**Comment by edwarnicke** [comment]
@LionelJouin woot!
