### ISSUE TITLE
MTU settings in the upcoming version of NSM 

### ISSUE THREAD

**Issue by mkomu** [networkservicemesh/networkservicemesh#2240]
## Expected Behavior

We have been benchmarking NSM and submitted a paper to IEEE. We expected to NSM to have MTU autodetection or at least a manual way to declare this in manifests, but this is not true. We would hope that this would be fixed in the new, upcoming version of NSM. 

## Current Behavior

Benchmarking of NSM leads to suboptimal results with iperf(3).

The workaround is to grant CAP_NET_ADMIN to containers and tweak it manually. The workaround is not suitable for production because it can introduce security vulnerabilities.

## Steps to Reproduce

As a prequisite, you will need will need a K8s cluster with one master and two workers, each running on bare metal or on VMs.

1. Start and connect a client and an endpoint using NSM
2. Make sure with "kubectl get pods -o wide" that the client and endpoint are running in different worker nodes
3. Install iperf3 in client and endpoint
4. Test that connectivity is working with ping
5. Run iperf3 -s in endpoint
6. Run iperf3 -c IP-OF-ENDPOINT in client
7. Repeat the above steps directly outside of Kubernetes in the worker nodes, and compare the results

Result: NSM performs poorly when compared to benchmarking directly on the worker nodes.

## Context

* Kubernetes Version: (irrelevant)
* NSM version: the current version of github (0.2)

**Comment by mkomu** [comment]
Have a look at:

https://github.com/projectcalico/calico/blob/master/networking/mtu.md

I recall we used MTU of 1450 with VXLAN but in K8s running on to of OpenStack VMs. I asked my colleague to comment here because he had a different set up (including a baremetal configuration).

With Wireguard, a safe value is 1420 (unlike in the previous link):

https://lists.zx2c4.com/pipermail/wireguard/2017-December/002201.html

**Comment by edwarnicke** [comment]
@mkomu Got it.  The most germane part for us there I think is:

> By default, {{site.prodname}} will auto-detect the correct MTU for your cluster based on node configuration and enabled networking modes.

Which was my best thought on how to approach the problem.   Last I checked the fancy MTU detection schemes were all broke in various ways, and so "Your sysadmin has thought hard about this problem, follow their lead" was the best choice I knew of... seems that's where calico landed as well (with the 'let folks override if need be').


From there subtracting the tunnel overhead if you traverse tunnels is pretty obvious :)  

With NSM we have both a slightly harder challenge but also a slightly easier solution.

Because NSM works cross domains, we may be stringing vWires from an on-prem cluster to a GKE cluster, or an EKS cluster, etc.  Best MTU choices may vary from domain to domain.  That's the harder problem part :)

The easier solution part is because they are *vWires*, we can take hinting along those.  Adding an MTU parameter to the Mechanism and allowing subsequent hops to decrement it by tunnel overhead, or bring it down to the level those hops can maximally handle gives us the ability to do a bit of 'MTU discovery' of our own.  Not perfect, but likely better.

Thoughts?

**Comment by mkomu** [comment]
Hi,

you made a good point about inter-domain NSM. I would have happy if this could even be set manually (preferably decoratively, without recompiling NSM) without using CAP_NET_ADMIN. The hints about possible MTU values for different tunnel types could be sprinkled into the documentation :)

As a first, easy stab on this problem, I would suggest lowering the default MTU in NSM to the lowest value (1390 in Calico docs) to make sure iperf and other fast file transfer tools work decently on NSM (albeit not optimal). I think this simple change could even be included in the existing 0.2 version.

**Comment by edwarnicke** [comment]
@mkomu My general rule of thumb is "Do the smartest thing you can do automatically, let a human manually override if need be"

Which brings me to the question: at what level would you be looking for an override?  Presumably at the cluster systemic level, but with the ability to set an MTU in the Mechanism... we could in principle allow the client to hint at least a 'smaller than you'd get by default' value for MTU per connection... thoughts?

**Comment by edwarnicke** [comment]
@mkomu we have other members of the community looking at iperf testing, including integrating iperf testing into our CI for the next gen NSM.  Would you be interested in being connected to those community members?

**Comment by mkomu** [comment]
> Which brings me to the question: at what level would you be looking for an override?

Interface level.

- MTU automatization makes sense only internally within a cluster (if even there?)
- In the interdomain NSM case, automation could select the lowest value (to be used, e.g., in a service chain extending to multiple clusters) but...
- It should be possible to override the MTU manually in the interdomain NSM case because it is difficult to guarantee a working solution

Sure, you can connect with iperf folks... dunno how much input I have though.

**Comment by edwarnicke** [comment]
@mkomu FYI... we do have MTU support landed now in the multi-repo:

https://github.com/networkservicemesh/sdk-vpp/pull/158

At baseline, it basically lets each hop along the way decrement the Connection.ConnectionContext.MTU if the current value is greater than what it can support.  The net result is that end to end on the vWire, we have a supportable MTU.  Its sort of like MTU discovery in that way.

Of course, as always, things can go wrong... the intervening underlay for example may fail to support the MTUs assigned to the actual physical interfaces on the servers for example... but hopefully that will be somewhat unusual, and I'm not sure we can do much about that.  Thoughts?

**Comment by mkomu** [comment]
Not familiar with the new codebase! Is it possible to manually override the MTU value? Using deployment file or NSM client request?

**Comment by edwarnicke** [comment]
@mkomu WRT override... the question is always *where* can you influence a value :)

For example:
1. A sending client can *always* set the Connection.ConnectionContext.MTU value before sending it to the NSE
2. A receiving NSE can *always* override the Connection.ConnectionContext.MTU as it passes through its hands.

Since the MTU is decided by accumulating those overrides on the outgoing direction of the call, and *implemented* on the return direction of the call... you can in fact achieve override.  In some sense the whole process is various components along the way overriding with their local information, for example "I'm doing vxlan over an interface with MTU $x so I will override to min($x-$vxlan_overhead,$existing_mtu_value) etc.

Does that make sense?

**Comment by mkomu** [comment]
Yes, makes sense. Thanks for all of your efforts and sorry for long delays in answering!

**Comment by edwarnicke** [comment]
@mkomu Can we close this issue?  Or is there more still to resolve here?

**Comment by mkomu** [comment]
Sure you can close this, thanks!
