### ISSUE TITLE
bug: no xconn DELETE received

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#583]
I'm deploying VM and k8s with vagrant files provided by the project.

Now I'm deploying nsm component manually:

```
k create -f k8s/conf/nsmd.yaml 
k create -f k8s/conf/vppagent-dataplane.yaml
k create -f k8s/conf/icmp-responder-nse.yaml
```

Then I'm deploying only one nsc, by setting replicas to 1 in nsc.yaml : 

```
k create -f k8s/conf/nsc.yaml
```

Then I start the crossconnect_monitor:

```
k create -f k8s/conf/crossconnect-monitor.yaml
```

I can then see the  INITIAL_STATE_TRANSFER message in the logs: 

```
*** 10.32.0.4:5001 INITIAL_STATE_TRANSFER Id:1 
id: "1"
payload: "IP"
local_source: <
  id: "1"
  network_service: "icmp-responder"
  mechanism: <
    type: KERNEL_INTERFACE
    parameters: <
      key: "name"
      value: "nsm1"
    >
    parameters: <
      key: "netnsInode"
      value: "4026532727"
    >
    parameters: <
      key: "workspace"
      value: "nsm-5"
    >
  >
  context: <
    key: "dst_ip"
    value: "10.20.1.2/30"
  >
  context: <
    key: "src_ip"
    value: "10.20.1.1/30"
  >
  labels: <
    key: "app"
    value: "icmp"
  >
>
local_destination: <
  id: "2"
  network_service: "icmp-responder"
  mechanism: <
    type: KERNEL_INTERFACE
    parameters: <
      key: "name"
      value: "nsm2"
    >
    parameters: <
      key: "netnsInode"
      value: "4026532651"
    >
    parameters: <
      key: "workspace"
      value: "nsm-7"
    >
  >
  context: <
    key: "dst_ip"
    value: "10.20.1.2/30"
  >
  context: <
    key: "src_ip"
    value: "10.20.1.1/30"
  >
>
```

If I remove  the nsc with "k delete -f k8s/conf/nsc.yaml" the nsc pod is correctly deleted but the crossconnect_monitor doesn't receive a DELETE message.

**Comment by edwarnicke** [comment]
We haven't yet implemented detection of Pods going away.  We intend to do that via detecting the inode going away in the /proc .

**Comment by edwarnicke** [comment]
# Detect NetNSInode disappearance

Each Connection comes with its netnsInode as a Parameter on its Mechanism.

When you can no longer find a /proc/*/ns/net file with that inode, then namespace (and thus the Pod) is gone, and the Connection should be deleted.

Currently, we create a [MonitorCrossConnectServer](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/monitor_crossconnect_server/monitor_crossconnect_server.go) [in the vppagent Server](https://github.com/ligato/networkservicemesh/blob/master/dataplane/vppagent/pkg/vppagent/server.go#L28).

I would suggest creating a MonitorNetNsInodeServer along the same lines.

It should be possible to write a type that matches the [MonitorCrossConnect_MonitorCrossConnectsServer](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/crossconnect/crossconnect.pb.go#L432) interface that is passed to the [MonitorCrossConnects](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/monitor_crossconnect_server/monitor_crossconnect_server.go#L51) call... and have MonitorNetNsInodeServer simply call monitor.MonitorCrossConnect to find out about new CrossConnects.

From there it can periodically scan through the /proc/*/ns/net collecting all the inode numbers, and see if we have any CrossConnect.Connections that are missing inode numbers.  If we are, it can call:

[Close](https://github.com/ligato/networkservicemesh/blob/master/dataplane/vppagent/pkg/vppagent/vppagent.go#L219) on that CrossConnect.

Since calling Close on a CrossConnect [fires the delete crossconnect monitor event](https://github.com/ligato/networkservicemesh/blob/master/dataplane/vppagent/pkg/vppagent/vppagent.go#L222), that should fix this bug.

**Comment by edwarnicke** [comment]
Oh... one other thing, look at the Go-like channel oriented pattern in MonitorCrossConnectServer rather than using Mutexes for concurrency

**Comment by edwarnicke** [comment]
Waiting on #617 and #622 to be fully finished.
