### ISSUE TITLE
NSM architecture review.

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#618]
Hi guys,

After some local discussions, and working on some parts of project like local NSM <-> remote NSM connectivity, 
I think we need to re-think of how architecture is designed right now. 
Since we are on very early stage we could have this more property designed and discussed.

Right now we are forcing an issue with too many "failure points" and requirement to have a transaction log on NSC -> NSE connection establishment and doing a proper rollback of all operations during Close, failures.

In case of NSC and NSE are on different nodes/etc we need to monitor troubles on two Dataplanes and in two NSMs and do a complicated distributed cleanup or think abour smart connection re-establish if it will be possible, (Should be possible in case of VxLan, not sure about all cases).

So main question here, do we really need a multiple NSM on every node? 

We already have a distributed NSMD-k8s NSE registry centralization point using a decentralized shared Key Value storage. 

Right now I've see following trouble points for us to handle connection:

<img width="1095" alt="connection_troubles" src="https://user-images.githubusercontent.com/477235/50236940-479bbf80-03ee-11e9-83be-d9c6999708fa.png">

And same for handling Close()

<img width="1054" alt="die_monitoring" src="https://user-images.githubusercontent.com/477235/50236964-53878180-03ee-11e9-9f82-ede37896c69b.png">

So I've have following idea to discuss:

* Have Decentralized registry will hold following information
	* NSE/Dataplanes registrations.
	* NSM liveness state.
	* ClientConnection's
		* Every operation we perform on establish, close, recovery of connection.
		* A current responsible NSM.

* Make NSMD a fully statelesss and have 1-M per cluster, we do not need it for be on every node.
	* Will check registry for other NSM die to continue their work.
	* Handle Client requests to put information into de-centralized storage.

* Dataplanes will be same on every done.
	* Will be connected to any of NSM for live monitoring.
	* In case of NSM die, will connect to any live one.
	* Will report CrossConnects, connection failures to any of NSM and start Close()/Recovery operations.

* Clients will connect to any suitable NSM for Requesting connection to NSE, and we respond async for execution of connection establish.
	* NSM will respond immidiatelly if there is no NSE.
	* NSM will respond async after all points will be configured.

And illustration of how it will work:

<img width="795" alt="stateless_proposal" src="https://user-images.githubusercontent.com/477235/50237010-68641500-03ee-11e9-9ab0-7089a0ad0621.png">

So I see a lot of complex scenarios will be easier to do and it would be more scallable and cluster oriented.

Also with this architecture we could have one NSM(fully centralyzed) variant with all information stored to ACID storage(file system) on local volume, so we are mostly independent of cluster implementation. Or we could use some of de-centralyzed data bases to implement this logic.

In this approach we do not need to have Dataplanes to hold any of cross connects, we could have monitoring API to be done on every NSM for all network.

Please share your thoughts.

**Comment by edwarnicke** [comment]
## Handling Failures during Setup of Remote Cross Connect

![image](https://user-images.githubusercontent.com/1455208/50252394-6d07d980-03ac-11e9-9ab1-8449e5bb4741.png)

1. NSC sends [local.Request(local.Connection)](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/local/networkservice/networkservice.proto#L34) to nsmd1
2. nsmd1 sends [FindNetworkService(FindNetworkServiceRequest)](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L66) to API Server (admittedly, indirectly via nsmd-k8s).
3. nsmd1 sends [remote.Request(remote.Connection)](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/remote/networkservice/networkservice.proto#L34) to nsmd2
4. nsmd2 sends [local.Request(local.Connection)](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/local/networkservice/networkservice.proto#L34) to the NSE Pod
5. NSE Pod Replies with a local.Connection
6. nsmd2 sends [crossconnect.Request(CrossConnect)](https://github.com/ligato/networkservicemesh/blob/master/dataplane/pkg/apis/dataplane/dataplane.proto#L20) to the Dataplane on Node2.
7. The Dataplane on Node2 Replies to nsm2 with a CrossConnect
8. nsmd2 Replies to nsmd1 with a remote.Connection
9. nsmd1 sends [crossconnect.Request(CrossConnect)](https://github.com/ligato/networkservicemesh/blob/master/dataplane/pkg/apis/dataplane/dataplane.proto#L20) to the Dataplane on Node1.
10. The Dataplane on Node1 Replies with a CrossConnect to nsmd1
11. nsmd1 Replies to NSC with a local.Connection

Any breakdown along this path can be fairly easily recovered in a distributed way, without need of a central transaction log or connection repository.

Recovering for something that goes wrong in the course of this flow is fairly simple:
1.  If something goes wrong when processing a 'Request', call 'Close()' on any downstream state you have created with your own Requests, and then return an error to the party that sent you a Request.

This actually works for more complex situations that are shown here (say for example the NSE Pod itself 'Requests' a Network Service in response to nsmd2's Request ... if it follows this simple rule, we get proper cleanup.

More in subsequent entries on how to reconcile more complex failure modes.

**Comment by edwarnicke** [comment]
## Handling NSC Dying

![image](https://user-images.githubusercontent.com/1455208/50255763-ddb4f300-03b8-11e9-9269-bb30feb7e74e.png)

1. NSC Dies
2. Dataplane Detects NSC is gone by detecting its NetNs is gone.  Marks local.Connection for NSC as state 'SRCDOWN' (TODO: File bug for local.Connection.State) in CrossConnect
3. MonitorCrossConnect returns from Dataplane on Node1 to nsmd1 a CrossConnectEvent of type Update with the CrossConnect with the updated Source Connection State.
4. nsmd1 extracts the CrossConnect.GetRemoteDestination() from the updated CrossConnect, and sends remote.Close(remote.Connection) to nsmd2
5. nsmd2 looks up in its memory the CrossConnect for which the Connection closed by nsmd2 is the Source.  It gets CrossConnect.LocalDestination() to get the Connection for the local NSE.  nsmd2 sends Close(Connection) to the NSE
6. NSE Pod Replies
7. nsmd2 sends Close(CrossConnect) to the Dataplane for Node2.
8. Dataplane on Node2 sends Reply
9. nsmd2  Replies to nsmd1
10. nsmd1 sends Close(CrossConnect) to the Dataplane on Node1
11. Dataplane on Node1 replies.

**Comment by edwarnicke** [comment]
## Handling NSE Dying (Autohealing)

![image](https://user-images.githubusercontent.com/1455208/50257869-d0046b00-03c2-11e9-803e-f9d81f0a0109.png)

1. NSE Dies
2. Dataplane2 detects the NetNS of NSE is gone
3. Dataplane2 returns MonitorCrossConnectEvent to nsmd2.  Type == Update, Con3.State == DST_DOWN.
4. nsmd2 sends RemoveNSE to API Server (indirectly)
5. nsmd2 sends Close(XC2) to Dataplane2
6. Dataplane2 Replies
7. nsmd2 returns MonitorConnectionEvent to nsmd1.  Type == DELETE
8. nsmd1 return MonitorConnectionEvent to NSC, Type == UPDATE, Con1.State == DST_DOWN.  Note: This is optional, as most NSC won't have called MonitorConnection.

Which leaves us with this:
![image](https://user-images.githubusercontent.com/1455208/50258019-72bce980-03c3-11e9-8fd6-3a9e6db82403.png)

![image](https://user-images.githubusercontent.com/1455208/50258049-8ff1b800-03c3-11e9-9f5b-b24e9db71f64.png)

9. nsmd1 sends FindNetworkService to the API Service (indirectly) to find a new NSE that provides the Network Service
10. nsmd1 sends Request(Con4) to nsmd3
11. nsmd3 sends Request(Con5) to the NSE
12. NSE sends Reply to NSE
13. nsmd3 sends Request(XC3) to Dataplane3
14. Dataplane3 Replies to nsmd3
15. nsmd3 returns Reply(Con4) to nsmd1
16. nsmd1 replaces Con2 in XC1.RemoteDestination with Con4 and sends Request(XC1) to Dataplane1
17.  Dataplane1 recognizes XC1 (by id) is an existing CrossConnect, and that XC1.Destination has been replaced.  Dataplane1 creates its end of Con4, and updates the XCon from Con1<->Con2 to Con1<->Con4 and then Dataplane1 Replies to nsmd1.

Note: #9-#15 is just the normal Connection Setup flow.

![image](https://user-images.githubusercontent.com/1455208/50258261-7309b480-03c4-11e9-8fb2-459afac4ba9a.png)

18. nsmd1 returns to NSC a MonitorConnectionEvent of Type == UPDATE and Con1.State == UP.

**Comment by edwarnicke** [comment]
One other note... it should be true within the Dataplane that translations from CrossConnects to things done in vppagent are purely deterministic.  This means that if the Dataplane needs to delete or recreate something from the CrossConnect, it can.

**Comment by edwarnicke** [comment]
Note: All images for this issue are here: https://docs.google.com/presentation/d/1TGNqhV41dl4RlCR3eeLeMIUnUeuU8m3LsrmdlPgX12c/edit#slide=id.g4a27cce692_0_0

In case you want to copy/modify.

**Comment by haiodo** [comment]
Thanks @edwarnicke, I've not supposed you will describe all cases with code links, I've not talk this is imposible, as we discussed we are working on re-think of how it should be, and variant we choose right now looks a bit more complicated when I expected.

Assume situation with remote connection is going on, NSM1 pass to NSM2, all is configured on NSM2 connection is returned to NSM1 and we start program Dataplane, and NSM1 node dies, in this case NSM2 will have partially configured connection and nobody knows it had, client will have error and will try again. So we somehow need to store into ACID of NSM1 about actions we perform.

Same if NSM2 node dies, but in this case we need to monitor from NSM1 about NSM2 cross connect changes, and we need to do so actually to be able to auto-heal. 

But this suddenly could happen for every NSM do monitor for every NSM in cluster, and this not looks good to me, will think more about this questions.

**Comment by edwarnicke** [comment]
@haiodo I'm halfway through writing those sorts of cases up... but net net... you don't have to monitor every nsmd, only every nsmd with which you are a peer (ie, have a connection).  You can learn that from the CrossConnects from the Dataplane if the nsmd restarts.

**Comment by haiodo** [comment]
Yes, but it could happen :-)

**Comment by edwarnicke** [comment]
@haiodo It can only happen if you have a connection from the nsmd to every other nsmd in the cluster.

Fundamentally... central DBs *lag* reality.  Peer connections *reflect* reality.

**Comment by haiodo** [comment]
I've not talk about centralyzed DB, I've think about we could use ETCD directly and for example NSMD will know NSMD he has connections to and monitor a ETCD values for liveness for this particular NSMD.

**Comment by edwarnicke** [comment]
@haiodo Fundamentally, NSM if able of cross-domain behavior... no central DB will ever be able to hold all relevant information, because not all of it is going to live within the view of a single Network Service Registry domain.  Similiar to how we can't store TCP connection state in a central DB for the world... because much of it is not in its view.

**Comment by edwarnicke** [comment]
@haiodo I could see using bolt to store some information locally.  Tends to be super light.  But the world still moves on between when the nsmd goes down and when it comes back... so you *still* have to synchronize with your peers to reflect reality.

**Comment by edwarnicke** [comment]
@haiodo As to nsmd liveliness... there's a reason we have a "LastSeenField" in the NSM CR... we don't use it well yet... but we do have it :)

**Comment by haiodo** [comment]
Ok, Thanks, will think more about this today.
Also I'm living in theory if something could happen, when users will make this happen for sure :-)

**Comment by edwarnicke** [comment]
@haiodo Not a bad theory :)  I also live in the theory that the state in the DB is not truth, it is at best hints of what was true in the past.  There's always a time lag between when you were last writing the the DB, and the now... so you still have to figure out what's *real*.

**Comment by edwarnicke** [comment]
## nsmd restarts

When an nsmd starts (or restarts) it currently waits for a Dataplane to Register.
Once the Dataplane has registered:

1. nsmd calls MonitorCrossConnects on Dataplane, and learns the set of all CrossConnects the Dataplane has.  
2. From the CrossConnects, nsmd can learn all of the CrossConnect.RemoteSource() and CrossConnect.RemoteDestinations().  Each of those are remote.Connections, and container the remote nsmd name, network service name, etc.
3. From that the nsmd can establish a new remote.MonitorConnection to each peer nsmd, learning what connections that peer believes itself to have with the nsmd.
4. from the CrossConnects, nsmd can learn all of the CrossConnect.LocalDestination() and thus the workspace.
5.  From the Workspace the nsmd can attempt to call local.MonitorConnections() on each workspace to get local NSE's opinions about their Connections. 

### Reconciling remotePeers
So for each remotePeers, the nsmd now has two views of reality: the remotePeer's, andthe Dataplane's.

These need to be reconciled.  The basic priniciples of reconciliation are:

1. If the Dataplane has a CrossConnect with a RemoteDestination() that is unknown to the remotePeers, first attempt to Request() the Connection learned from the Dataplane.  If that fails, carry out the autohealing procedure.
2. If the Datplane has a CrossConnect with a RemoteSource() that is unknown to the remotePeers, Close the Connection with the local NSE and Close the CrossConnect with the Dataplane
3. If the remotePeers has a Connection with the nsmd for which the nsmd is listed as the source nsmd the Connection is unknown to the Dataplane, send Close(Connection) to the remotePeers for those Connections


### Reconciling localPeers

For each localPeer, the nsmd now has two views of reality: the localPeer's, and the Dataplane's.

These need to be reconciled.  The basic principles of reconciliation are:

1.  If the Dataplane has a CrossConnect with a LocalDestination() that is unknown to the local NSE, Request() that local.Connection to the local NSE.
2. If the localPeer has a Connection that is unknown to the Dataplane, Close() the Connection with the local NSE.

**Comment by edwarnicke** [comment]
@haiodo I have given some thoughts to having the vppagent-dataplane *process* squirrel away some data in bolt, in case the vppagent-dataplane process dies for some reason (and is restarted by supervisord) and the vppagent and vpp processes keep on going.

**Comment by edwarnicke** [comment]
Some notes on keeping the state in process.

Have a look at what @lobkovilya did in #605 in terms of having the MonitorXXXServer be both the in memory store of state and *also* the thing that notifies any possible in process listeners for state changes.

**Comment by haiodo** [comment]
Yes, it was based on our internal discussions.

**Comment by haiodo** [comment]
Questions is just for entire node dead handling ( NSMD + Dataplane) die together.

**Comment by edwarnicke** [comment]
@haiodo If the entire Node goes down... its all gone, there's nothing to recover :)  All NSC and NSEs on the Node are also gone.

**Comment by edwarnicke** [comment]
@haiodo The remotePeers of the nsmd on the Node that goes down will either:

1.  Not be able to re-establish their MonitorConnection calls after a reasonable period of time
2.  Re-establish them to an nsmd that believes it has no Connections with that remotePeer, the remotePeer can then take appropriate action:
2.1 If the remotePeer has a Connection with the nsmd as a Destination, it can first try to reconnect to the NSE, and if that fails, autoheal for its local NSC
2.2 Ifthe remotePeer has a Connection with the nsmd as a Source, it can Close() the connections with its local NSEs.

**Comment by lobkovilya** [comment]
@edwarnicke After continuous discussion we discovered some cases that won't be covered by monitors between nsmd instances. 

In case of Node goes down and it had NSE. Who will notify registry about NSE dies? Also when Node just disconnected from cluster and then comes back. Should it update registry about NSE that it has?

So maybe if we have distributed system we also should have distributed registry? Every nsmd will know only about NSEs that it has on the Node. It will share information about NSEs with nsmd on other nodes. It can be implemented as some routing protocol. I think it helps us to avoid situation when registry has NSE that already dies.

What do think about it?

**Comment by edwarnicke** [comment]
@lobkovilya Good job on thinking through the corner cases!

Let's walk through your cases

**Case 1.** The Node goes down, and there are NSEs in the Network Service Registry (in the K8s case, the K8s API Server as NSE Custom Resources), and the Node does not come back up.
**Case 2.** The Node is partitioned from the Network Service Registry (in the K8s case, the K8s master), and has had NSEs register while partitioned from the master.  

In **Case1**, the thought was to use [NetworkServiceManager.last_seen](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L36).  Note: While the field is present now, we do not properly update it.  The basic algorithm would be to select an update interval, update last_seen every update interval, and consider the Network Service Manager gone if it has been more than 3*${update interval} since its last_seen.  This algorithm could be applied by an nsmd on lookup, it could check for timedout NSMs before selecting NSEs (each of which has an NSM).  One could also imagine having a Deployment independently monitoring and cleaning up NSMs (and their attendant NSEs) if they are timed out.

Now I know @platoff has enough experience (and I suspect @haiodo does to) to object:  "What about clock skew?!" and "What if different nsmds have different opinions about what the update interval is?!".  To which I would respond: do you guys have ideas to make the last_seen mechanism more robust to those issues? :)

In **Case2** lets look at other effects of Node disconnect from master.  First, new Pods cannot be scheduled to a Node that is disconnected from master.  So that eliminates one class of situations that might result in NSEs not being properly registered.  So we are left with the case that a Pod runs, then the Node is partitioned from the master, and then the Pod seeks to register as an NSE.  In that case, the Pod calls RegisterNSE on the nsmd, the nsmd calls RegisterNSE on the nsmd-k8s, the nsmd-k8s seeks to register the NSE CR in the API Server.   nsmd-k8s will (eventually) fail producing an error.  That error should be passed back to the nsmd in response to its RegisterNSE call.  The nsmd should then pass that error back to the NSE in response to its RegisterNSE call.  So we are left with the case that no one, not the Pod, not the nsmd, and not the Network Service Registry believes that NSE has been registered.  In other words: Consistency.  So from the CAP Theorem, we choose C and P (Consistency and Partition) over Availability (you can't register an NSE if you are Partitioned from your Network Service Registry).  I'm open to discussing whether a different CAP choice is better, but this is at least a *valid* one :)

As to a fully distributed Registry.  Its an interesting thought.  Right now, we have a *partial* mesh between peers actively interacting with each other.  If there are 5000 nsmds in the Cluster (for 5k Nodes, which is the current K8s scale at the top) and a particular nsmd has connections with 10 of them, it only has 10 peers.  If we go full mesh, each nsmd would have need 5k peers.  If we start bringing in things from other clusters, and other eNSM cases it gets even bigger.  There are some real aspects of what we are doing in NSM that bring in routing kinds of wisdom, but it is probably not true that we want to go *full* mesh.

**Comment by edwarnicke** [comment]
@lobkovilya @haiodo @platoff You guys are doing a good job thinking through the robustness architecture, asking good questions, bringing good ideas.  It sounds like you are close to having through the corner cases.  

When you get there, it would be good to break this down into fairly granular issues and start working through them.  There are lots of things here that can be done as small independent pieces.   Since we are attracting more contributors, it's super helpful to have granular issues that folks can pick up if they get to them before you do.

**Comment by edwarnicke** [comment]
Note on Connection.State.

When discussing Connect.State, I talked about states UP and DST_DOWN.  I think we can get away with just states UP and DOWN, with DOWN being the default enum value.  Note: This means a recipient of a "Request" will need to insure the Connections are marked "UP" before returning.

**Comment by platoff** [comment]
Hi folks, nice to see this discussion, and I personally still think we should have basically two types of components - NSM per cluster(s) and NSM Dataplanes (per node), for HA reasons there could be N NSMs per cluster, but conceptually it's a single nsm per cluster(s) (or single nsm per cluster and nsms from different clusters connected together). 

Why? The decision to go distributed (nsm per node) opened a can of worms, and I believe this would reveal many problems in the future to catch on. Distributed systems are hard (even simple distributed system is hard). As a big fan of distributed systems I'd be happy to work on one, but for NSM case I do not see any benefit of distributed architecture - centralized solution would be easier to implement, more performant (scales better), and has more power in terms of future capabilities because of having centralized view/control of cluster from the single place. 

If there is any benefit of the distributed solution versus a centralized one, I'll definitely change my view on this. As for performance scalability, we can go with some tests, but at this time, simple counting number of calls in distributed scenario, including calls to single-point-of-failure-and-performance-bottleneck k8s CRD database, we can see that centralized solution will be a way faster.

Potentially, fully distributed scenario (without k8s CRD database) can scale better, but only in case of bottleneck (centralized NSM) will not be able to perform its operations fast, which probably starts at millions of requests per second in a cluster, which is never. 

The current design is not actually a distributed system, but a set of clients (nodes) communicating via shared database, and performance of the whole system is limited by the performance of that database. Switching to centralized NSM would have similar benefits as old desktop systems communicating through shared file database switch to client-server (application server) architecture (which is centralized nsm).

The current design very much resembles the hardware-based network, where NSM is chassis deployed to each node, and dataplanes installed into NSM slots. But we're clearly doing Software Defined Networking. Quick googling for what SDN is shows me this article (I'm pretty sure there are much better articles), but I'd like to quote this one to support the idea we should disaggregate dataplane and nsm. https://www.sdxcentral.com/sdn/definitions/inside-sdn-architecture/

![sdn-architecture](https://user-images.githubusercontent.com/474163/50342796-df9bc500-0524-11e9-8394-2faf782a341a.png)

> In the SDN architecture, the splitting of the control and data forwarding functions is referred to as “disaggregation,” because these pieces can be sourced separately, rather than deployed as one integrated system. This architecture gives the applications more information about the state of the entire network from the controller, as opposed to traditional networks where the network is application aware.

> The SDN architecture APIs are often referred to as northbound and southbound interfaces, defining the communication between the applications, controllers, and networking systems. A Northbound interface is defined as the connection between the controller and applications, whereas the Southbound interface is the connection between the controller and the physical networking hardware. **Because SDN is a virtualized architecture, these elements do not have to be physically located in the same place**.

**Comment by matrohon** [comment]
Hi, great discussions here.

My 2cts: having a centralized NSMd probably makes sense as long as you stay in a NSM domain. But it seems we will still need some NSMd to NSMd interactions once we'll introduce eNSM use case, or Multi domain connectivity.

For instance, if we take the secure-intranet-connectivity use case, for now we only manage pods inside a single cluster. But we can easily think that the other side of the vpn (in the intranet) will be managed by a pod that terminates the vpn connection, and that this pod will also be managed by the NSMd located in the cluster of the intranet. The creation of the two pods (one in the cloud, one in the intranet) managing the vpn connectivity dynamically could happen through a negotiation between the two NSMd (one in the cloud domain, one in the intranet domain), as it is done currently between NSMd.

Yet, I'm not sure this use case is in the scope of NSM :)

**Comment by edwarnicke** [comment]
@platoff I totally get your thinking here, and why a centralized NSMd sounds like a good idea.  It's the same idea that led the entire networking industry off the cliff in the first gen of SDN.

I was personally very deeply involved in that run at SDN, being a major contributor to the initial OpenFlow plugin on the OpenDaylight controller, doing a bunch of the work on the core of the current implementation of the ovsdb plugin in OpenDaylight, and contributing to many applications there.  I've got a lot of code under my fingernails in SDN.

I also followed from there the evolution of most other SDN solutions.  Centralized controllers sounded like the right way to a bunch of super smart folks.

Experience is a harsh teacher.  What pretty much everyone in SDN learned over time is that:
1.  Central controllers don't scale
2. Central controllers don't perform
3. HA for controllers is super super super hard to do right

What's evolved from that experience is that most SDN solutions have evolved into distributed systems that looks a lot like what we are doing here:

1. Central storage of critical, slow changing, intent information and information, and advertisement of globally relevant operational data
2. Moving decision making and canonical operational data as close to the dataplane that touches the packets as possible.

If you look at what we are doing here with NSM, it super analogous to TCP + DNS, which scales well, performs well, and is stable.  Moving the NSMd centrally is sort of analogous to moving the connection setup and teardown parts of the TCP centrally.

The really interesting new element of the system is that unlike the TCP stack, where if the kernel crashes you loose the whole Node, or to upgrade the TCP stack you have to take down the whole Node, in NSM we have the opportunity to survive the restart of the local nsmd or dataplane.  This introduces what looks like additional complexity, but its not "The system is more complex than TCP + DNS", its "The system has more opportunities than TCP + DNS, because we are not welded to the kernel".

**Comment by edwarnicke** [comment]
@matrohon NSM is definitely interested in the use case of collaborating with things outside the cluster.  See the external NSM (eNSM) stuff in the K8s presentations :)

**Comment by matrohon** [comment]
The main issue about centralized controllers that are not scaling is mainly an issue about maintaining states in databases. When you begin to have a lot of datas in the DB, updates and concurrents lookup can become costly. Is this the kind of scale issue you were having at Opendayligth @edwarnicke ?

Here we have three main components : 
- the registry (k8s CRD)
- the controller (nsmd)
- the dataplane-agent

If we go along with your TCP/DNS analogous, the registry is the DNS, while the TCP stack is divided into:
- the controller for the connection establishment (SYN/SYNACK/ACK)
- the dataplane-agent for packet forwarding

It seems all of those components are stateful, am I wrong? As shown during the discussion, it is painful to maintain.

If I'm correct, the NSMd should be stateless, as it is only there to connect NSC to NSE via a lookup in the registry.

If we talk about a new design for NSM, let's talk about the totally decentralized way (except for the registry) : don't you think it's possible to remove the NSMd, and move the server part inside endpoint pods, and the client part inside NSM client init-containers? This way, we would mimic the TCP/DNS model @edwarnicke  mentioned

**Comment by platoff** [comment]
I think current architecture can’t beat centralized nsmd (cnsmd) architecture in terms of scalability. 

Let’s write down calls required to connect NSC to NSE in current architecture:

1a. NSC calls NSMD1
2a. NSMD1 calls local nsmd-k8s
3a. Local nsmd-k8s performs 1..N calls to k8s master 
4a. NSMD1 calls NSMD2
5a. NSMD2 calls NSE
6a. NSMD2 calls Dataplane2
7a. NSMD1 calls Dataplane1

Centralized NSMD calls would be the following:

1b. NSC calls CNSMD
2b. CNSMD calls NSE
3b. CNSMD calls Dataplane2
4b. CNSMD calls Dataplane1

In current architecture we assume calls are distributed among different NSMD/Dataplane instances, so it’s hard to impossible to understand limitations of the whole system without real simulation, but call (3a) is a clear bottleneck in the current architecture:

First, this is a call to shared resource (k8s API server) and performance of the whole system limited to k8s API server performance. 

Second, it’s highly inefficient. Inefficient in the same way like finding a record in the database by reading a whole database file and iterating through to find a record. 

Current @haiodo tests show that finding NSM via registry takes 1-1.5 second when there are 6000 NSEs registered.

Any distribution of workload in the system would not let the system to work faster than nsmd-k8s -> k8s API server interaction. The obvious solution to make this interaction faster is client-server (application server), which is CNSMD.

So call 3a in current architecture which takes seconds would be replaced with call 1a, which is essentially single hash table lookup on CNSMD side. 

I’d like to say that registry is a bottleneck here, and replacing registry with any other database (file) would not improve the situation much. If we would replace it with own registry server (which is a better registry with fast lookups) — a kind of half-cooked CNSMD, it would render current NSMDs obsolete, since they will be simple proxying calls back and forth and it’s better to move all NSMD logic to CNSMD.

I believe current NSM performance with k8s registry is OK for all possible deployment scenarios. My point here is not about milliseconds, but I’d like to argue that nothing can beat CNSMD in terms of scalability and reliability as well as simplicity. So the question is why we’re making the system complex and semi-distributed without scalability benefits?

**Comment by lobkovilya** [comment]
Also I’d like to add, that service mesh approach is very good in terms of proxing of traffic as Envoy or Istio do. But our NSC only creates single Request() to NSMD, gets interfaces injected and uses them to send traffic. So we have no advantages of this nsmd-per-node architecture. 
 But since we are going to implement nodes interaction in different clusters it would suit our purposes better to use nsmd-ped-cluster approach.

**Comment by edwarnicke** [comment]
@platoff Good breakdown.  I agree, 3a (Local nsmd-k8s performs 1..N calls to k8s master) is a bottleneck.

I'd suggest we look at dealing with this in two steps:

1. Caching - [K8s API Machinery already has easy to use caching](https://medium.com/firehydrant-io/stay-informed-with-kubernetes-informers-4fda2a21da9e).  And the ability to [have event handlers called on updates](http://borismattijssen.github.io/articles/kubernetes-informers-controllers-reflectors-stores).  A preliminary look suggest we could use an [IndexInformer](https://godoc.org/k8s.io/client-go/tools/cache#NewIndexerInformer) to respond to updates from the K8s API Server to compute (and store for retrieval) the [FindNetworkServiceResponse](https://github.com/ligato/networkservicemesh/blob/master/controlplane/pkg/apis/registry/registry.proto#L47) for all network_service_names.  This makes the lookup in nsmd-k8s basically as fast as an in memory map lookup.
2. Make nsmd's ${hostname}:${port} configurable for the nsmd-k8s.  As you've no doubt noticed, *eventually* as the number of Nodes grows, the notification of nsmd-k8s per Node can become a bottleneck.  For small to medium sized clusters, collocating with the nsmd in the same Pod still probably makes sense.  For large clusters, you want to be able to deploy some number of replicas less than one per Node for nsmd-k8s and put them behind a K8s Service.  For this to work, the nsmd's ${hostname}:${port} for the nsmd-k8s has to be configurable.

#1 should fix the scalability issue you pointed out in 3a.  #2 should allow us to handle the new bottleneck of notifications to nsmd-k8s (when it becomes an issue).
