### ISSUE TITLE
Some questions related to NSM

### ISSUE THREAD

**Issue by quangtamle** [networkservicemesh/networkservicemesh#634]
Hi everyone,

I have some questions related to the NSM:

1. Where is k8s api server in the deployment ??? Is it k8s master or integrated in k8s master ???
2. Could I create one more worker node ??? if yes, how could I do that ??? (ex: modified vagrant file...)
3. About dataplane, vswitch you mentioned in the slides is the contiv-vpp, isnt it ???
4. As far as I am concerned, Network Service Mesh is inspired by Istio. Then NSMD in NSM plays role as side car proxy in Istio, doesnt it ??? and which component in k8s master plays role as Mixer in Istio ???

Thank you in advance

**Comment by nickolaev** [comment]
@quangtamle find my answers below:

1. Yes it runs on the master node

2. You can, please refer to Vagrant's docs here: https://www.vagrantup.com/docs/multi-machine/ I guess you should also modify some of the othere files in Makefile machinery (*.mk). FYI - currently both master and worker nodes run workloads, i.e. master is not k8s API only node.

3. The vswitch is based on https://github.com/ligato/vpp-agent

4. Let's say that NSM is inspired by Istio, rather than implementing the same architecture choices. NSMD is the local (per-node) management agent. It may be seen as a functional equivalent of the sidecar proxy, but it is not per pod.
NSM implements a decentralized model of configuring the service mesh. As such, there is no central entity like Mixer, that holds the full state of the mesh. In its current implementation, NSM uses the K8s registry (effectively etcd) as a central repository for registering the Endpoints and then the connection decisions are done by each NSMD independently from the rest of the mesh.

You might be interested in reading and maybe participating in this long issue: https://github.com/ligato/networkservicemesh/issues/618

@edwarnicke or @fkautz may be more accurate here.

**Comment by quangtamle** [comment]
Hi @nickolaev 

Thank your for your answers, after going further, I have another questions:

1. As far as i am concerned, the k8s api server (NSM register) can be considered as routing table for this node and serves only for this node (locally). Am I right ???
2. At the beginning how can k8s api server know how to reach to the other NSMD in general ???
3. What NSC (network service client) and NSE (network service endpoint) could be ??? a running application, a database or...

Thank you in advances

**Comment by edwarnicke** [comment]
@quangtamle 

1.  Think of it as a (Network) Service Registry.  K8s provides a (non-Network) Service Registry with the 'Service' and 'Endpoints' resources in the API Service.  Please note: we happen to use the K8s API Server for this registry, but it doesn't *have* to be kept there.  Nothing in the architecture welds us the the K8s API server.  The K8s API server happens to provide really amazingly good API machinery, so we take advantage of that.
2. Note: The K8s API Server simply stores resource information.  It doesn't reach anything.  The Network Service Managers talk to the K8s API Server.
3.  NSC is basically any Pod which needs a Network Service.  So if I have an application Pod that needs 'secure-intranet-connectivity', that would be an NSC.  An NSE is simply something that *provides* a Network Service.  It could be any Pod (or even non-Pod) thing which processes the L2/L3 (Ethernet/IP) payloads from the NSC.
4. They tend to be Pods, yes.  But nothing *requires* them to be.  Your NSE could be provided by a Pod, the physical network, a VM outside the cluster etc.  There's a *lot* of flexibility in the architecture.  We tend to talk about them as Pods for the most part because its easiest to understand, and most relavent in the K8s community.
5.  NSM is super flexible about the NSMD (Network Service Mesh Dataplane).  We happen to have done it here with vpp and vppagent, because its super simple and easy.  But fundamentally, as long as a dataplane exposes the [NSM Dataplane API](https://github.com/ligato/networkservicemesh/blob/master/dataplane/pkg/apis/dataplane/dataplane.proto), anything that can cross connect packets will do.  The NSM Dataplane API is super simple.  In specific, it would be quite easy for Contiv-VPP to provide the NSM Dataplane, as it is already using vpp and vppagent.  There are advantages to having a single vswitch providing both CNI and NSM Dataplane and owning the NIC.  Its not required, but it is advantageous.

**Comment by quangtamle** [comment]
Dear @edwarnicke @nickolaev 

Thank you so much for your infomation !!!

2. At the beginning, how can K8s API server get information from nodes and how K8s API servers get information between each other (i mean another K8s API servers from the other clusters) ???

**Comment by edwarnicke** [comment]
@quangtamle 

2.  The nsmd on each node registers itself (and NSEs) with the K8s API server
3.  NSM does point to point L2/L3 connections between NSEs, not bridge domains.

**Comment by quangtamle** [comment]
Dear @edwarnicke 
 Thank you for your answer !!!

3. Sorry for misunderstand because in the video, you used the "brigde domain" in the demo part so that I want to make sure about this.

By the way, could you let this issue open, so whenever I have any questions I can ask in this issue for easy tracking ???

Thank you in advance

**Comment by quangtamle** [comment]
Dear @edwarnicke 

I have a question about your demo in the first video (introduction NSM). After you built the "bridge-domain" code, it is created 3-4 connections. It looks like those connections are created randomly because I didnt notice you specify any kind of information (IP address, name of pods...) about source and destination of those connections.

So if I want to specify the source and destination of one connection, what kind of parameters I specify ???

Thank you

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

I have some more concerns related to NSM:

1. How pods are configured to use the NSM « L2/L3 connections » to offer their services. Is it outside the code of NSM or not ? 
2. How « end points »  are identified when NSC makes request to the NSMD ?
3. 
![pastedgraphic-1](https://user-images.githubusercontent.com/43220759/51171930-69377c00-18b2-11e9-82a4-5e75f3569aa0.png)
For example I have a topology like this. A want to have a L2 connection to D using NSM. In the point of view of network, the connection has to go through B or C, then how NSM handle B or C in this case ???
In my opinion, I think NSM will make a point-to-point connection from A to B/C and from B/C to D. Am I right ???

Thank you in advances !!!
Have a nice day !!!

**Comment by nickolaev** [comment]
@quangtamle The way your picture will be implemented is as follows:

 - you deploy 1x A pod 2xreplicas of the B pod (that is what you have as B and C) and 1x D pod

 - you define a Networks Service similar to https://github.com/ligato/networkservicemesh/blob/master/k8s/conf/secure-intranet-connectivity.yaml Let's call it NS1

 - your A pod will request NS1 service with a label of "app=B" (remember that C is just a replica of B). The NSMD will select B or C by round-robin algorithm (because both expose "app=B" label).

 - And then B or C (whoever is selected) will request a connection to NS1 with "app=D"

Let me know if that explains it.

**Comment by quangtamle** [comment]
Dear @nickolaev 

Thank you for your answer !!! it is answered my questions but it also lead to another questions.

In the point of view of the operator of service A, he/she only need to make a request to the app=D and do not need to care what is in the middle and NSM will help them do all the rest, Am I right ???

If it is a "yes" then your first (deploying those pods) and third bullet points are the job of NSM, arent they ???

When you said NSE are identified by the label "app=...", so are those labels unique ??? what if there are 2 identical label but different functions (that may be happended) ???

In case, there are troubles in the middle (B or C is died or unreachable), who is gonna be the troubleshooter ??? To be more clear, As far as I am concerned, NSM has its own autohealing procedures but in the long run with the development of NSM and the complexity of Service Mesh, do we need someone who are dedicated for NSM like network engineer for instance ??? (sorry if it is a stupid question :)) )

Thank you in advances !!!

**Comment by quangtamle** [comment]
Dear @nickolaev,

Thank you for your answer !!! it is answered my questions but it also lead to another questions.

4. In the point of view of the operator of service A, he/she only need to make a request to the app=D and do not need to care what is in the middle and NSM will help them do all the rest, Am I right ???

5. If it is a "yes" then your first (deploying those pods) and third bullet points are the job of NSM, arent they ???

6. When you said NSE are identified by the label "app=...", so are those labels unique ??? what if there are 2 identical label but different functions (that may be happended) ???

7. In case, there are troubles in the middle (B or C is died or unreachable), who is gonna be the troubleshooter ??? To be more clear, As far as I am concerned, NSM has its own autohealing procedures but in the long run with the development of NSM and the complexity of Service Mesh, do we need someone who are dedicated for NSM like network engineer for instance ??? (sorry if it is a stupid question :)) )

Thank you in advances !!!

**Comment by nickolaev** [comment]
@quangtamle it really depends how the Network Service is described. In `secure-intranet-connectivity` example we have a default (think no match) rule where all requests match. So when A asks for NS1 (without any labels) the selector will choose the default route, which actually has a destination match app=B. 

For sure the deployment of A (being the NS client) is up to the user of NSM. In the future, we will be able to spawn services on demand (think (B or C) and D), but for now this is also a matter of the service operator to ensure is present.

Having different functions with the same labels is not a problem as long as they implement different services. So when they register, for example B1 can say "I implement NS1 with app=B" and then B2 can say "I implement NS2 with app=B". There is no conflict as the selector will first select by the service name and then by label matching.

The autohealing is envisioned as a feature of NSMD and is something we have in our roadmap. As for supporting NSM, I believe it should be treated as a part of the K8s network infrastructure. It will have enough monitoring tools and will possibly be integrated in the external management platforms.

**Comment by quangtamle** [comment]
Dear @nickolaev @edwarnicke 

Thank you for your answer !!!

Sorry but back to the Intro presentation slide, My case is look like Sarah's case. Sarah will be the one who write "secure-intranet-connectivity.yaml" file  to request the secure connection. According to the "secure-intranet-connectivity.yaml", she has to know what is between her pod and NSE (VPN GW). What if Sarah or A (in my case) doesnt know what are between NSC (her pod or A) and NSE (VPN GW or D), then how can she/ A write the file???

Because As far as i am concerned, for the sake of NSM, the NSC only need to know the NSE, dont need to care how many pods the connect go through.

Sorry if my question is so stupid !!!

Thank you in advances

**Comment by nickolaev** [comment]
@quangtamle Nope, Sarah actually knows that there is a NS `secure-intranet-connectivity` that someone deployed and maintains for her. Even if she needs to deploy it - she would get the yaml from the network setup team that know all the details.

**Comment by quangtamle** [comment]
Dear @nickolaev 

Thank you so much for your answer !!! now everything get more clearer now !!!

So in her point of view, she only need to know NSC and NSE. There is a team which take care all her requests. Interesting !!! Sorry that I dont know.

Thank you so much for your time !!!

**Comment by edwarnicke** [comment]
@quangtamle Is this issue resolved from your point of view?  May I close it?

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Sorry about that but May you let this issue open, so whenever I havìe any questions I can ask in this issue for easy tracking ???

If it is not inappropriate, i will close it.

Thank you so much

**Comment by edwarnicke** [comment]
All good :)

**Comment by quangtamle** [comment]
Thank you so much

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

I have a general question about connection in NSM and maybe for k8s.

Can we allocate bandwidth for a specific connection between 2 pods (on-demand) ??? if no then NSM can address this problem ???

Thank you in advance

**Comment by edwarnicke** [comment]
@quangtamle Can you allocate bandwidth between two servers in your DC? ;)  End to end?

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

In fact, in DC, I can do that. In physical layer point of view, I can choose cooper cable or fiber cable for BW. In layer 2/3 point of view (suppose there is a switch or router between them), i can apply QoS policy to allocate BW on the connected interface.

What I mean here is the service point of view, for example L3VPN, client pay for the BW they request. Or Sarah (in NSM) she want a secure connection to the a specific pod for different purposes such as for transmiting data vs ssh to that pod so the BW in two cases should be different. This is what I mean.

**Comment by edwarnicke** [comment]
@quangtamle I meant end to end in the DC... NIC to switch is comparatively easy.  And yes, you can mark packets with QoS bits ( definitely an area we could explore for overlay tunnels).  But if I have two random servers somewhere in the DC, *guaranteed* bandwidth between them gets to be a very complex problem that requires a *lot* of cooperation with the NetOps folks.

I'd be super interested in discussing what we can do to come up with a good QoS story for NSM... but I'd be shocked if we successfully get to end to end guaranteed bandwidth :)

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Ok, let put guaranteed bandwidth aside. Suppose I want a server with 6 Gbps BW uplink so I will easily choose fiber cable instead of cooper one. As the operator, I need to know how much traffic my server uplink can handle, in case, there are traffic congestion I can find some solutions such upgrade uplink or steering traffic into another server.... :)). So I think it will be the same with the pods :))

**Comment by edwarnicke** [comment]
Are you getting at the "I have x uplink bandwidth, I want to be able to
guarantee y of it to this workload" problem?  If so, much more tractable
:)

Ed

**Comment by quangtamle** [comment]
Yes yes, to be clearer, I have x uplink bandwidth, in the peak time, I can use all of x uplink bw with congestion.

**Comment by edwarnicke** [comment]
OK, so is this uplink shared with the CNI plugin, or just plugged into the
NSM dataplane?

**Comment by quangtamle** [comment]
Well in general, both cases can be happended. So if you dont mind, could you tell me both cases ???

**Comment by edwarnicke** [comment]
If CNI owns the NIC, and we are sharing with it... then there is no good way to police CNI :(

If NSM Dataplane has its own NIC... that we could police. The interesting trick is actually what should the semantics look like for users to express their intent, and how to we work that down through the scheduler :)

**Comment by quangtamle** [comment]
Dear @edwarnicke ,

Sorry but as far as I remembered, NSM dataplane is super flexible so what if it can be CNI plugin.

"NSM Dataplane has its own NIC... that we could police" which NSM Dataplane you mean here ???

Sorry I just want to be clear :))

**Comment by quangtamle** [comment]
Dear @nickolaev @edwarnicke ,

After I ran the command "make k8s-logs", CPU get 100% in all cores for a long time. Is it normal ???

![image](https://user-images.githubusercontent.com/43220759/53403306-a748b500-39b3-11e9-86e6-b2b5daf6bd9e.png)

As it is shown in the picture. Where can I get the log ???

Thank you in advances

**Comment by quangtamle** [comment]
Dear @edwarnicke @nickolaev 

In the NSM architecture, NSM can run even on physical machines (like routers...) and VM so what kind of form of NSM in those situations (e.g. is it a software, a platform, or some scripts...???)

Thank you in advances
