### ISSUE TITLE
Questions about services and interfaces

### ISSUE THREAD

**Issue by Napoleon0621** [networkservicemesh/networkservicemesh#807]
This is somewhat a question about NSM structure and mechanisms. 

From my previous knowledge, under most current circumstances, one NSC pod normally has a single interface connecting to a NSE pod. In case there is need for multiple network services, NSM implements something like a chained network function just like the "secure-intranet-connectivity" example.

My question is: under the Telco scenario, is it likely that a NSC runs different services which connects to more than one NSE pods through multiple interfaces?  If that's the case, how will the service know which interface is the right one to go?
 
Thanks,
JZhai

**Comment by matrohon** [comment]
This is an interesting question that has also been raised by ramki during weekly meetings.
I don't see anything preventing a pod to be connected to several network services. This pod will end up having several interfaces, one per service.

This could be achieved by adding several [annotations to your client descriptor](https://github.com/networkservicemesh/networkservicemesh/blob/master/k8s/conf/vpn-gateway-nsc.yaml#L22).
Then one NSC per annotation could be run. A NSC can ask for a specific [name](https://github.com/networkservicemesh/networkservicemesh/blob/master/sdk/client/client.go#L44) for the interface, so that the service running in the pod will know which interface is connected to which network service.

A limit to this model is the ability for network services and corresponding NSE to inject IPs ans routes in the pod. Then, we have to be careful about overlapping IPs/routes.

**Comment by edwarnicke** [comment]
@Napoleon0621 In NSM, an NSC can request any number of L2/L3 Connections to any Number of Network Services.  Each L2/L3 Connection will show up in the NSC as a separate interface.  

Please also note that an NSC can request connections to Network Services at any point in its lifecycle (not just the beginning).  Normal app Pods won't likely do this... but CNFs almost certainly will :)

**Comment by Napoleon0621** [comment]
Thank you guys, that's super helpful. 
One thing to add, whenever an NSC wants to make a new request or make changes to its current connection, all it needs to to is to change its configuration file and redeploy itself. Am I right?
