### ISSUE TITLE
Add exclude_prefix check to SDK

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#841]
## Overview

This is a sub-issue of #838, see that issue for more context.

The SDK should have a check to ensure that IPAM has not allocated IPs or Routes from the exclude_prefix list in the connection context.  This check should be added to all of the examples in NSM.

**Comment by nickolaev** [comment]
My assumption is the change should happen somewhere along these lines:
https://github.com/networkservicemesh/networkservicemesh/blob/master/sdk/endpoint/composite/ipam.go#L56

**Comment by edwarnicke** [comment]
Yes.  Probably best to write some handy helper functions that could be used in all kinds of IPAM Composables... 

Note, net.IPNet has some helpful functions for testing whether something is in a given Prefix.

**Comment by edwarnicke** [comment]
@rdimitrov How are we doing getting this resolved?

**Comment by rdimitrov** [comment]
@edwarnicke It's WIP as it turned out that the IP allocation algorithm needs to be updated as well.

**Comment by lobkovilya** [comment]
We need more carefully choose prefix that will be split. Candidates could be categorized in three types:
1. Without any intersection with `excludePrefixes`
2. Have some excluded prefixes as a part
3. Fully contained in one of `excludePrefixes`

I suppose Type1 is most preferable for splitting. Type2 is the second priority and Type3 is immediately discarded. In case of absent of Type1 we dial with Type2. And here is the most complicated part - we should carefully check is it possible to find prefix of required size in type2-candidate:

Let's assume that type2-candidate has size of prefix equal to `C`, we trying to extract prefix with size equal `R` we know that `R > C`. Also we have excluded prefixes with sizes `E1`, `E2` ... some of them bigger than R, some smaller. Always can think about prefixes as nodes in tree:
![image](https://user-images.githubusercontent.com/12110261/55904778-d8dfad80-5bfa-11e9-90b3-97898184051a.png)

Excluded prefix eliminates the whole subtree (red color nodes on image):
![image](https://user-images.githubusercontent.com/12110261/55905669-aafb6880-5bfc-11e9-8906-2348df4f3f1d.png)

Easy to understand that candidate has `2^(R-C)` prefixes of required size `R`, in example - `2^2 = 4` prefixes of size `R` in candidate of size `C`. If there are some excluded prefixes with sizes smaller then `R` (`E1` in example) they will exclude `2^(R-E)` prefixes of size `R`, in example - `2^1 = 2`. 

![image](https://user-images.githubusercontent.com/12110261/55906474-9029f380-5bfe-11e9-9890-ab14c7cdc1ac.png)

What about excluded prefixes that longer than `R` (`E2` and `E3` in example), we should take first `R` bits from them and figure out how many unique sequences we have. Blue node on image shows prefix that excluded because of `E2` and `E3`.
![image](https://user-images.githubusercontent.com/12110261/55906929-9d93ad80-5bff-11e9-8622-9797334913b3.png)

So if we sum "blue" and "red" nodes on tree level `R` and compare it with `2^(R-C)` we will understand is it possible to find requested prefix in type2-candidate. 

It's just a draft of algorithm, I'm pretty sure it is not optimal, but I hope it helps.

**Comment by rdimitrov** [comment]
@lobkovilya Impressive! 💯 

I've noticed, though, that the focus of the issue has slightly shifted from verifying the allocated IPs to redesigning the IPAM algorithm.

In that sense, I'm thinking if it makes sense to basically exclude all the `excludedPrefix` entries from the available `impl.prefixes` pool before doing the IPAM in the Request() handler, for ex. - 
```go
ice.prefixPool.ExcludePrefixes(request.Connection.Context.ExcludedPrefixes)
```

Perhaps, it'd be less prone to errors when the IP ranges are missing from the pool of available addresses beforehand. What are your thoughts on that?

**Comment by lobkovilya** [comment]
@rdimitrov that's good idea! And it sounds much easier to implement :) 
But just make sure that you are doing prefix exclude on the copy of `prefixPool`, since excludePrefixes are vary from request to request

**Comment by rdimitrov** [comment]
@edwarnicke We can close this one as #888 got merged 👍

**Comment by nickolaev** [comment]
@rdimitrov I will close this one, but please consider fixing the predictability of the unit tests.
