### ISSUE TITLE
Testing NSM with IPv6 payloads

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#920]
## Overview

NSM is architecturally designed to carry payloads including IPv6.  Currently, we do not have testing of that.  Please add icmp and vpn test cases using Ipv6 payloads.

**Comment by rdimitrov** [comment]
Wanted to share an update about the current status 👍 

After enabling the use case testing with IPv6 in #962, faced an issue where the IPv6 support is disabled inside both the client and NSE containers. 
This causes a failure when the dataplane starts to inject the interfaces due to a "permission denied" error. There's a similar issue explaining what happens in detail - https://github.com/containernetworking/cni/issues/531 

After discussing this with @nickolaev, he opened an issue against `vpp-agent` describing the problem and suggesting a way to fix it - https://github.com/ligato/vpp-agent/issues/1308

I assume for the time being we can consider the issue as blocked until the issue on the `vpp-agent` side is resolved. _I'll share a comment about that in the PR as well._

**Comment by edwarnicke** [comment]
@ondrej-fabry  Could you have a look at  ligato/vpp-agent#1308 ?  Would be good to get a fix sooner rather than later :)

**Comment by ondrej-fabry** [comment]
@edwarnicke lookin at it :) will ping you when ready

**Comment by edwarnicke** [comment]
@rdimitrov Has this issue been resolved?

**Comment by rdimitrov** [comment]
@edwarnicke It is resolved, yes 👍 Apologies for not updating the issue, somehow it got forgotten...

**Comment by nickolaev** [comment]
#962 fixes this
